// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efarfpxtjvtrglzcfsmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmYXJmcHh0anZ0cmdsemNmc21tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDIyOTQsImV4cCI6MjA2NzMxODI5NH0.wHaEd5YgwTSz9ElUlXMhXOyQZpOblhO_gu8VlvqYsIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});